var annotated =
[
    [ "AudioStreamInfo", "classprimo_1_1codecs_1_1_audio_stream_info.html", "classprimo_1_1codecs_1_1_audio_stream_info" ],
    [ "Buffer", "classprimo_1_1codecs_1_1_buffer.html", "classprimo_1_1codecs_1_1_buffer" ],
    [ "ByteArrayParameter", "classprimo_1_1avblocks_1_1_byte_array_parameter.html", "classprimo_1_1avblocks_1_1_byte_array_parameter" ],
    [ "ErrorInfo", "classprimo_1_1avblocks_1_1_error_info.html", "classprimo_1_1avblocks_1_1_error_info" ],
    [ "GenericParameter", "classprimo_1_1avblocks_1_1_generic_parameter.html", "classprimo_1_1avblocks_1_1_generic_parameter" ],
    [ "LicenseInfo", "classprimo_1_1license_1_1_license_info.html", "classprimo_1_1license_1_1_license_info" ],
    [ "MediaBuffer", "classprimo_1_1codecs_1_1_media_buffer.html", "classprimo_1_1codecs_1_1_media_buffer" ],
    [ "MediaBufferParameter", "classprimo_1_1avblocks_1_1_media_buffer_parameter.html", "classprimo_1_1avblocks_1_1_media_buffer_parameter" ],
    [ "MediaInfo", "classprimo_1_1avblocks_1_1_media_info.html", "classprimo_1_1avblocks_1_1_media_info" ],
    [ "MediaPin", "classprimo_1_1avblocks_1_1_media_pin.html", "classprimo_1_1avblocks_1_1_media_pin" ],
    [ "MediaPinList", "classprimo_1_1avblocks_1_1_media_pin_list.html", "classprimo_1_1avblocks_1_1_media_pin_list" ],
    [ "MediaSample", "classprimo_1_1codecs_1_1_media_sample.html", "classprimo_1_1codecs_1_1_media_sample" ],
    [ "MediaSocket", "classprimo_1_1avblocks_1_1_media_socket.html", "classprimo_1_1avblocks_1_1_media_socket" ],
    [ "MediaSocketList", "classprimo_1_1avblocks_1_1_media_socket_list.html", "classprimo_1_1avblocks_1_1_media_socket_list" ],
    [ "MetaAttribute", "classprimo_1_1codecs_1_1_meta_attribute.html", "classprimo_1_1codecs_1_1_meta_attribute" ],
    [ "MetaAttributeList", "classprimo_1_1codecs_1_1_meta_attribute_list.html", "classprimo_1_1codecs_1_1_meta_attribute_list" ],
    [ "Metadata", "classprimo_1_1codecs_1_1_metadata.html", "classprimo_1_1codecs_1_1_metadata" ],
    [ "MetaPicture", "classprimo_1_1codecs_1_1_meta_picture.html", "classprimo_1_1codecs_1_1_meta_picture" ],
    [ "MetaPictureList", "classprimo_1_1codecs_1_1_meta_picture_list.html", "classprimo_1_1codecs_1_1_meta_picture_list" ],
    [ "Parameter", "classprimo_1_1avblocks_1_1_parameter.html", "classprimo_1_1avblocks_1_1_parameter" ],
    [ "ParameterList", "classprimo_1_1avblocks_1_1_parameter_list.html", "classprimo_1_1avblocks_1_1_parameter_list" ],
    [ "Reference", "classprimo_1_1_reference.html", "classprimo_1_1_reference" ],
    [ "Stream", "classprimo_1_1_stream.html", "classprimo_1_1_stream" ],
    [ "StreamInfo", "classprimo_1_1codecs_1_1_stream_info.html", "classprimo_1_1codecs_1_1_stream_info" ],
    [ "StreamInfoEnum", "classprimo_1_1codecs_1_1_stream_info_enum.html", "classprimo_1_1codecs_1_1_stream_info_enum" ],
    [ "Transcoder", "classprimo_1_1avblocks_1_1_transcoder.html", "classprimo_1_1avblocks_1_1_transcoder" ],
    [ "TranscoderCallback", "classprimo_1_1avblocks_1_1_transcoder_callback.html", "classprimo_1_1avblocks_1_1_transcoder_callback" ],
    [ "VideoStreamInfo", "classprimo_1_1codecs_1_1_video_stream_info.html", "classprimo_1_1codecs_1_1_video_stream_info" ]
];