var hierarchy =
[
    [ "Param.Encoder.Audio", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio.html", null ],
    [ "Param.Decoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder.html", null ],
    [ "Param.Encoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder.html", null ],
    [ "ErrorInfo", "class_primo_software_1_1_a_v_blocks_1_1_error_info.html", null ],
    [ "Param.Encoder.Video.H264", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_h264.html", null ],
    [ "Library", "class_primo_software_1_1_a_v_blocks_1_1_library.html", null ],
    [ "MediaBuffer", "class_primo_software_1_1_a_v_blocks_1_1_media_buffer.html", null ],
    [ "MediaInfo", "class_primo_software_1_1_a_v_blocks_1_1_media_info.html", null ],
    [ "MediaPin", "class_primo_software_1_1_a_v_blocks_1_1_media_pin.html", null ],
    [ "MediaSample", "class_primo_software_1_1_a_v_blocks_1_1_media_sample.html", null ],
    [ "MediaSocket", "class_primo_software_1_1_a_v_blocks_1_1_media_socket.html", null ],
    [ "Meta", "class_primo_software_1_1_a_v_blocks_1_1_meta.html", null ],
    [ "MetaAttribute", "class_primo_software_1_1_a_v_blocks_1_1_meta_attribute.html", null ],
    [ "Metadata", "class_primo_software_1_1_a_v_blocks_1_1_metadata.html", null ],
    [ "MetaPicture", "class_primo_software_1_1_a_v_blocks_1_1_meta_picture.html", null ],
    [ "MimeType", "class_primo_software_1_1_a_v_blocks_1_1_mime_type.html", null ],
    [ "Param.Encoder.Audio.MPEG1", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_m_p_e_g1.html", null ],
    [ "Param.Encoder.Video.MPEG2", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_m_p_e_g2.html", null ],
    [ "Param", "class_primo_software_1_1_a_v_blocks_1_1_param.html", null ],
    [ "ParameterList", "class_primo_software_1_1_a_v_blocks_1_1_parameter_list.html", null ],
    [ "PinConnection", "class_primo_software_1_1_a_v_blocks_1_1_pin_connection.html", null ],
    [ "StreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_stream_info.html", [
      [ "AudioStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_audio_stream_info.html", null ],
      [ "VideoStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_video_stream_info.html", null ]
    ] ],
    [ "Transcoder", "class_primo_software_1_1_a_v_blocks_1_1_transcoder.html", null ],
    [ "TranscoderContinueEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_continue_event_args.html", null ],
    [ "TranscoderProgressEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_progress_event_args.html", null ],
    [ "TranscoderStatusEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_status_event_args.html", null ],
    [ "Param.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video.html", null ],
    [ "Param.Encoder.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video.html", null ],
    [ "Param.Encoder.Audio.Vorbis", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_vorbis.html", null ],
    [ "Param.Encoder.Audio.WMA", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_w_m_a.html", null ]
];