var annotated =
[
    [ "Param.Encoder.Audio", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio.html", null ],
    [ "AudioStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_audio_stream_info.html", "class_primo_software_1_1_a_v_blocks_1_1_audio_stream_info" ],
    [ "Param.Decoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder" ],
    [ "Param.Encoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder.html", null ],
    [ "ErrorInfo", "class_primo_software_1_1_a_v_blocks_1_1_error_info.html", "class_primo_software_1_1_a_v_blocks_1_1_error_info" ],
    [ "Param.Encoder.Video.H264", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_h264.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_h264" ],
    [ "Library", "class_primo_software_1_1_a_v_blocks_1_1_library.html", "class_primo_software_1_1_a_v_blocks_1_1_library" ],
    [ "MediaBuffer", "class_primo_software_1_1_a_v_blocks_1_1_media_buffer.html", "class_primo_software_1_1_a_v_blocks_1_1_media_buffer" ],
    [ "MediaInfo", "class_primo_software_1_1_a_v_blocks_1_1_media_info.html", "class_primo_software_1_1_a_v_blocks_1_1_media_info" ],
    [ "MediaPin", "class_primo_software_1_1_a_v_blocks_1_1_media_pin.html", "class_primo_software_1_1_a_v_blocks_1_1_media_pin" ],
    [ "MediaSample", "class_primo_software_1_1_a_v_blocks_1_1_media_sample.html", "class_primo_software_1_1_a_v_blocks_1_1_media_sample" ],
    [ "MediaSocket", "class_primo_software_1_1_a_v_blocks_1_1_media_socket.html", "class_primo_software_1_1_a_v_blocks_1_1_media_socket" ],
    [ "Meta", "class_primo_software_1_1_a_v_blocks_1_1_meta.html", "class_primo_software_1_1_a_v_blocks_1_1_meta" ],
    [ "MetaAttribute", "class_primo_software_1_1_a_v_blocks_1_1_meta_attribute.html", "class_primo_software_1_1_a_v_blocks_1_1_meta_attribute" ],
    [ "Metadata", "class_primo_software_1_1_a_v_blocks_1_1_metadata.html", "class_primo_software_1_1_a_v_blocks_1_1_metadata" ],
    [ "MetaPicture", "class_primo_software_1_1_a_v_blocks_1_1_meta_picture.html", "class_primo_software_1_1_a_v_blocks_1_1_meta_picture" ],
    [ "MimeType", "class_primo_software_1_1_a_v_blocks_1_1_mime_type.html", "class_primo_software_1_1_a_v_blocks_1_1_mime_type" ],
    [ "Param.Muxer.MP4", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_muxer_1_1_m_p4.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_muxer_1_1_m_p4" ],
    [ "Param.Encoder.Audio.MPEG1", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_m_p_e_g1.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_m_p_e_g1" ],
    [ "Param.Encoder.Video.MPEG2", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_m_p_e_g2.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_m_p_e_g2" ],
    [ "Param.Muxer", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_muxer.html", null ],
    [ "Param", "class_primo_software_1_1_a_v_blocks_1_1_param.html", null ],
    [ "ParameterList", "class_primo_software_1_1_a_v_blocks_1_1_parameter_list.html", null ],
    [ "PinConnection", "class_primo_software_1_1_a_v_blocks_1_1_pin_connection.html", "class_primo_software_1_1_a_v_blocks_1_1_pin_connection" ],
    [ "StreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_stream_info.html", "class_primo_software_1_1_a_v_blocks_1_1_stream_info" ],
    [ "Transcoder", "class_primo_software_1_1_a_v_blocks_1_1_transcoder.html", "class_primo_software_1_1_a_v_blocks_1_1_transcoder" ],
    [ "TranscoderContinueEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_continue_event_args.html", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_continue_event_args" ],
    [ "TranscoderProgressEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_progress_event_args.html", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_progress_event_args" ],
    [ "TranscoderStatusEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_status_event_args.html", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_status_event_args" ],
    [ "Param.Encoder.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video.html", null ],
    [ "Param.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video" ],
    [ "VideoStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_video_stream_info.html", "class_primo_software_1_1_a_v_blocks_1_1_video_stream_info" ],
    [ "Param.Encoder.Audio.Vorbis", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_vorbis.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_vorbis" ],
    [ "Param.Encoder.Audio.WMA", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_w_m_a.html", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_w_m_a" ]
];