var hierarchy =
[
    [ "Preset.Video.AndroidPhone", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_android_phone.html", null ],
    [ "Preset.Video.AndroidTablet", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_android_tablet.html", null ],
    [ "Preset.Video.AppleLiveStreaming", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_apple_live_streaming.html", null ],
    [ "Preset.Video.AppleTV", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_apple_t_v.html", null ],
    [ "Preset.Audio", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio.html", null ],
    [ "Param.Encoder.Audio", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio.html", null ],
    [ "Preset.Audio.AudioCD", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_audio_c_d.html", null ],
    [ "Preset.Video.BDAV", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_b_d_a_v.html", null ],
    [ "Param.Video.Crop", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video_1_1_crop.html", null ],
    [ "Param.Decoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder.html", null ],
    [ "Param.Video.Deinterlacing", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video_1_1_deinterlacing.html", null ],
    [ "Preset.Video.DVD", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_d_v_d.html", null ],
    [ "Preset.Audio.DVD", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_d_v_d.html", null ],
    [ "Param.Encoder", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder.html", null ],
    [ "EventArgs", null, [
      [ "TranscoderContinueEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_continue_event_args.html", null ],
      [ "TranscoderProgressEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_progress_event_args.html", null ],
      [ "TranscoderStatusEventArgs", "class_primo_software_1_1_a_v_blocks_1_1_transcoder_status_event_args.html", null ]
    ] ],
    [ "Preset.Video.Fast", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_fast.html", null ],
    [ "Param.Video.FrameRateConverter", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video_1_1_frame_rate_converter.html", null ],
    [ "Preset.Audio.Generic", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic.html", null ],
    [ "Preset.Video.Generic", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_generic.html", null ],
    [ "Param.Decoder.Video.H264", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder_1_1_video_1_1_h264.html", null ],
    [ "Param.Encoder.Video.H264", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_h264.html", null ],
    [ "ICloneable", null, [
      [ "ErrorInfo", "class_primo_software_1_1_a_v_blocks_1_1_error_info.html", null ],
      [ "StreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_stream_info.html", [
        [ "AudioStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_audio_stream_info.html", null ],
        [ "DataStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_data_stream_info.html", null ],
        [ "VideoStreamInfo", "class_primo_software_1_1_a_v_blocks_1_1_video_stream_info.html", null ]
      ] ]
    ] ],
    [ "IDisposable", null, [
      [ "MediaInfo", "class_primo_software_1_1_a_v_blocks_1_1_media_info.html", null ],
      [ "Transcoder", "class_primo_software_1_1_a_v_blocks_1_1_transcoder.html", null ],
      [ "UnmanagedMediaBuffer", "class_primo_software_1_1_a_v_blocks_1_1_unmanaged_media_buffer.html", null ]
    ] ],
    [ "Preset.Video.iPad", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1i_pad.html", null ],
    [ "Preset.Video.iPhone", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1i_phone.html", null ],
    [ "Preset.Video.iPod", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1i_pod.html", null ],
    [ "Library", "class_primo_software_1_1_a_v_blocks_1_1_library.html", null ],
    [ "Preset.Audio.Generic.M4A", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_m4_a.html", null ],
    [ "MediaBuffer", "class_primo_software_1_1_a_v_blocks_1_1_media_buffer.html", null ],
    [ "MediaPin", "class_primo_software_1_1_a_v_blocks_1_1_media_pin.html", null ],
    [ "MediaSample", "class_primo_software_1_1_a_v_blocks_1_1_media_sample.html", null ],
    [ "MediaSocket", "class_primo_software_1_1_a_v_blocks_1_1_media_socket.html", null ],
    [ "Meta", "class_primo_software_1_1_a_v_blocks_1_1_meta.html", null ],
    [ "MetaAttribute", "class_primo_software_1_1_a_v_blocks_1_1_meta_attribute.html", null ],
    [ "Metadata", "class_primo_software_1_1_a_v_blocks_1_1_metadata.html", null ],
    [ "MetaPicture", "class_primo_software_1_1_a_v_blocks_1_1_meta_picture.html", null ],
    [ "MimeType", "class_primo_software_1_1_a_v_blocks_1_1_mime_type.html", null ],
    [ "Preset.Audio.Generic.MP3", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_m_p3.html", null ],
    [ "Preset.Video.Generic.MP4", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_generic_1_1_m_p4.html", null ],
    [ "Param.Muxer.MP4", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_muxer_1_1_m_p4.html", null ],
    [ "Preset.Video.Fast.MP4", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_fast_1_1_m_p4.html", null ],
    [ "Param.Encoder.Audio.MPEG1", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_m_p_e_g1.html", null ],
    [ "Param.Encoder.Video.MPEG2", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video_1_1_m_p_e_g2.html", null ],
    [ "Param.Muxer", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_muxer.html", null ],
    [ "Preset.Audio.Generic.OggVorbis", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_ogg_vorbis.html", null ],
    [ "Param.Video.Pad", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video_1_1_pad.html", null ],
    [ "Param", "class_primo_software_1_1_a_v_blocks_1_1_param.html", null ],
    [ "PinConnection", "class_primo_software_1_1_a_v_blocks_1_1_pin_connection.html", null ],
    [ "Preset", "class_primo_software_1_1_a_v_blocks_1_1_preset.html", null ],
    [ "Preset.Audio.Generic.WMA.Professional", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_w_m_a_1_1_professional.html", null ],
    [ "Param.Video.Resize", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video_1_1_resize.html", null ],
    [ "Preset.Audio.Generic.WMA.Standard", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_w_m_a_1_1_standard.html", null ],
    [ "Preset.Video.VCD", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_v_c_d.html", null ],
    [ "Param.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_video.html", null ],
    [ "Param.Decoder.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder_1_1_video.html", null ],
    [ "Preset.Video", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video.html", null ],
    [ "Param.Encoder.Video", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_video.html", null ],
    [ "Param.Encoder.Audio.Vorbis", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_vorbis.html", null ],
    [ "Param.Decoder.Video.H264.VUI", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_decoder_1_1_video_1_1_h264_1_1_v_u_i.html", null ],
    [ "Preset.Video.Generic.WebM", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_video_1_1_generic_1_1_web_m.html", null ],
    [ "Param.Encoder.Audio.WMA", "class_primo_software_1_1_a_v_blocks_1_1_param_1_1_encoder_1_1_audio_1_1_w_m_a.html", null ],
    [ "Preset.Audio.Generic.WMA", "class_primo_software_1_1_a_v_blocks_1_1_preset_1_1_audio_1_1_generic_1_1_w_m_a.html", null ]
];